#!/usr/bin/php
<?php

if (!isset($argv[1])) {
    echo 'Error: Please specify a command.' . PHP_EOL;
    exit;
}

$command = $argv[1];

if ($command === 'install') {
    shell_exec('/usr/bin/php app.php core rebuildFrameworkCache');
}