#!/usr/bin/env php
<?php

if (!isset($argv[1])) {
    echo 'Error: Please specify a command.' . PHP_EOL;
    exit;
}

$command = $argv[1];

if ($command === '--install') {
    shell_exec(__DIR__ . '/turbo core rebuildFrameworkCache');
    
    define('EXECUTION_DISABLED', true);
    require_once(__DIR__ . '/app.php');
    
    // Activate the installation module
    $framework->getModuleManager()->activateModule('\\Zepi\\Installation\\Turbo');
    $framework->getRuntimeManager()->executeEvent('\\Zepi\\Installation\\ExecuteInstallation');
    $framework->getModuleManager()->deactivateModule('\\Zepi\\Installation\\Turbo');
} else {
    require_once(__DIR__ . '/app.php');
}