<?php $this->printTemplate('\\Zepi\\Web\\AccessControl\\Templates\\Header'); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-24">
            <h1>Welcome!</h1>
        </div>
        <div class="col-md-24">
            <div class="message success">
                Welcome to zepi Turbo!
            </div>
        </div>
    </div>
</div>


<?php $this->printTemplate('\\Zepi\\Web\\AccessControl\\Templates\\Footer'); ?>
